export default [
  "Blues---Boogie Woogie",
  "Blues---Chicago Blues",
  "Blues---Country Blues",
  "Blues---Delta Blues",
  "Blues---East Coast Blues",
  "Blues---Electric Blues",
  "Blues---Harmonica Blues",
  "Blues---Jump Blues",
  "Blues---Louisiana Blues",
  "Blues---Memphis Blues",
  "Blues---Modern Electric Blues",
  "Blues---Piano Blues",
  "Blues---Piedmont Blues",
  "Blues---Rhythm & Blues",
  "Blues---Texas Blues",
  "Brass & Military---Brass Band",
  "Brass & Military---Marches",
  "Brass & Military---Military",
  "Brass & Military---Pipe & Drum",
  "Children's---Educational",
  "Children's---Nursery Rhymes",
  "Children's---Story",
  "Classical---Baroque",
  "Classical---Choral",
  "Classical---Classical",
  "Classical---Contemporary",
  "Classical---Early",
  "Classical---Impressionist",
  "Classical---Medieval",
  "Classical---Modern",
  "Classical---Neo-Classical",
  "Classical---Neo-Romantic",
  "Classical---Opera",
  "Classical---Operetta",
  "Classical---Oratorio",
  "Classical---Post-Modern",
  "Classical---Renaissance",
  "Classical---Romantic",
  "Classical---Twelve-tone",
  "Electronic---Abstract",
  "Electronic---Acid",
  "Electronic---Acid House",
  "Electronic---Acid Jazz",
  "Electronic---Ambient",
  "Electronic---Baltimore Club",
  "Electronic---Bassline",
  "Electronic---Beatdown",
  "Electronic---Berlin-School",
  "Electronic---Big Beat",
  "Electronic---Bleep",
  "Electronic---Breakbeat",
  "Electronic---Breakcore",
  "Electronic---Breaks",
  "Electronic---Broken Beat",
  "Electronic---Chillwave",
  "Electronic---Chiptune",
  "Electronic---Dance-pop",
  "Electronic---Dark Ambient",
  "Electronic---Darkwave",
  "Electronic---Deep House",
  "Electronic---Deep Techno",
  "Electronic---Disco",
  "Electronic---Disco Polo",
  "Electronic---Donk",
  "Electronic---Doomcore",
  "Electronic---Downtempo",
  "Electronic---Drone",
  "Electronic---Drum n Bass",
  "Electronic---Dub",
  "Electronic---Dub Techno",
  "Electronic---Dubstep",
  "Electronic---Dungeon Synth",
  "Electronic---EBM",
  "Electronic---Electro",
  "Electronic---Electro House",
  "Electronic---Electroacoustic",
  "Electronic---Electroclash",
  "Electronic---Euro House",
  "Electronic---Euro-Disco",
  "Electronic---Eurobeat",
  "Electronic---Eurodance",
  "Electronic---Experimental",
  "Electronic---Footwork",
  "Electronic---Freestyle",
  "Electronic---Future Jazz",
  "Electronic---Gabber",
  "Electronic---Garage House",
  "Electronic---Ghetto",
  "Electronic---Ghetto House",
  "Electronic---Ghettotech",
  "Electronic---Glitch",
  "Electronic---Glitch Hop",
  "Electronic---Goa Trance",
  "Electronic---Grime",
  "Electronic---Halftime",
  "Electronic---Hands Up",
  "Electronic---Happy Hardcore",
  "Electronic---Hard Beat",
  "Electronic---Hard House",
  "Electronic---Hard Techno",
  "Electronic---Hard Trance",
  "Electronic---Hardcore",
  "Electronic---Hardstyle",
  "Electronic---Harsh Noise Wall",
  "Electronic---Hi NRG",
  "Electronic---Hip Hop",
  "Electronic---Hip-House",
  "Electronic---House",
  "Electronic---IDM",
  "Electronic---Illbient",
  "Electronic---Industrial",
  "Electronic---Italo House",
  "Electronic---Italo-Disco",
  "Electronic---Italodance",
  "Electronic---J-Core",
  "Electronic---Jazzdance",
  "Electronic---Juke",
  "Electronic---Jumpstyle",
  "Electronic---Jungle",
  "Electronic---Latin",
  "Electronic---Leftfield",
  "Electronic---Lento Violento",
  "Electronic---Makina",
  "Electronic---Minimal",
  "Electronic---Minimal Techno",
  "Electronic---Modern Classical",
  "Electronic---Musique Concrète",
  "Electronic---Neo Trance",
  "Electronic---Neofolk",
  "Electronic---New Age",
  "Electronic---New Beat",
  "Electronic---New Wave",
  "Electronic---Noise",
  "Electronic---Nu-Disco",
  "Electronic---Power Electronics",
  "Electronic---Progressive Breaks",
  "Electronic---Progressive House",
  "Electronic---Progressive Trance",
  "Electronic---Psy-Trance",
  "Electronic---Rhythmic Noise",
  "Electronic---Schranz",
  "Electronic---Sound Collage",
  "Electronic---Speed Garage",
  "Electronic---Speedcore",
  "Electronic---Synth-pop",
  "Electronic---Synthwave",
  "Electronic---Tech House",
  "Electronic---Tech Trance",
  "Electronic---Techno",
  "Electronic---Trance",
  "Electronic---Tribal",
  "Electronic---Tribal House",
  "Electronic---Trip Hop",
  "Electronic---Tropical House",
  "Electronic---UK Funky",
  "Electronic---UK Garage",
  "Electronic---Vaporwave",
  "Electronic---Witch House",
  "Folk, World, & Country---Aboriginal",
  "Folk, World, & Country---African",
  "Folk, World, & Country---Andalusian Classical",
  "Folk, World, & Country---Andean Music",
  "Folk, World, & Country---Appalachian Music",
  "Folk, World, & Country---Basque Music",
  "Folk, World, & Country---Bhangra",
  "Folk, World, & Country---Bluegrass",
  "Folk, World, & Country---Cajun",
  "Folk, World, & Country---Canzone Napoletana",
  "Folk, World, & Country---Carnatic",
  "Folk, World, & Country---Catalan Music",
  "Folk, World, & Country---Celtic",
  "Folk, World, & Country---Chacarera",
  "Folk, World, & Country---Chinese Classical",
  "Folk, World, & Country---Chutney",
  "Folk, World, & Country---Copla",
  "Folk, World, & Country---Country",
  "Folk, World, & Country---Cretan",
  "Folk, World, & Country---Dangdut",
  "Folk, World, & Country---Fado",
  "Folk, World, & Country---Flamenco",
  "Folk, World, & Country---Folk",
  "Folk, World, & Country---Funaná",
  "Folk, World, & Country---Gamelan",
  "Folk, World, & Country---Ghazal",
  "Folk, World, & Country---Gospel",
  "Folk, World, & Country---Griot",
  "Folk, World, & Country---Hawaiian",
  "Folk, World, & Country---Highlife",
  "Folk, World, & Country---Hillbilly",
  "Folk, World, & Country---Hindustani",
  "Folk, World, & Country---Honky Tonk",
  "Folk, World, & Country---Indian Classical",
  "Folk, World, & Country---Kaseko",
  "Folk, World, & Country---Klezmer",
  "Folk, World, & Country---Laïkó",
  "Folk, World, & Country---Luk Thung",
  "Folk, World, & Country---Maloya",
  "Folk, World, & Country---Mbalax",
  "Folk, World, & Country---Min'yō",
  "Folk, World, & Country---Mizrahi",
  "Folk, World, & Country---Nhạc Vàng",
  "Folk, World, & Country---Nordic",
  "Folk, World, & Country---Népzene",
  "Folk, World, & Country---Ottoman Classical",
  "Folk, World, & Country---Overtone Singing",
  "Folk, World, & Country---Pacific",
  "Folk, World, & Country---Pasodoble",
  "Folk, World, & Country---Persian Classical",
  "Folk, World, & Country---Phleng Phuea Chiwit",
  "Folk, World, & Country---Polka",
  "Folk, World, & Country---Qawwali",
  "Folk, World, & Country---Raï",
  "Folk, World, & Country---Rebetiko",
  "Folk, World, & Country---Romani",
  "Folk, World, & Country---Salegy",
  "Folk, World, & Country---Sea Shanties",
  "Folk, World, & Country---Soukous",
  "Folk, World, & Country---Séga",
  "Folk, World, & Country---Volksmusik",
  "Folk, World, & Country---Western Swing",
  "Folk, World, & Country---Zouk",
  "Folk, World, & Country---Zydeco",
  "Folk, World, & Country---Éntekhno",
  "Funk / Soul---Afrobeat",
  "Funk / Soul---Bayou Funk",
  "Funk / Soul---Boogie",
  "Funk / Soul---Contemporary R&B",
  "Funk / Soul---Disco",
  "Funk / Soul---Free Funk",
  "Funk / Soul---Funk",
  "Funk / Soul---Gogo",
  "Funk / Soul---Gospel",
  "Funk / Soul---Minneapolis Sound",
  "Funk / Soul---Neo Soul",
  "Funk / Soul---New Jack Swing",
  "Funk / Soul---P.Funk",
  "Funk / Soul---Psychedelic",
  "Funk / Soul---Rhythm & Blues",
  "Funk / Soul---Soul",
  "Funk / Soul---Swingbeat",
  "Funk / Soul---UK Street Soul",
  "Hip Hop---Bass Music",
  "Hip Hop---Beatbox",
  "Hip Hop---Boom Bap",
  "Hip Hop---Bounce",
  "Hip Hop---Britcore",
  "Hip Hop---Cloud Rap",
  "Hip Hop---Conscious",
  "Hip Hop---Crunk",
  "Hip Hop---Cut-up/DJ",
  "Hip Hop---DJ Battle Tool",
  "Hip Hop---Electro",
  "Hip Hop---Favela Funk",
  "Hip Hop---G-Funk",
  "Hip Hop---Gangsta",
  "Hip Hop---Go-Go",
  "Hip Hop---Grime",
  "Hip Hop---Hardcore Hip-Hop",
  "Hip Hop---Hiplife",
  "Hip Hop---Horrorcore",
  "Hip Hop---Hyphy",
  "Hip Hop---Instrumental",
  "Hip Hop---Jazzy Hip-Hop",
  "Hip Hop---Kwaito",
  "Hip Hop---Miami Bass",
  "Hip Hop---Pop Rap",
  "Hip Hop---Ragga HipHop",
  "Hip Hop---RnB/Swing",
  "Hip Hop---Screw",
  "Hip Hop---Thug Rap",
  "Hip Hop---Trap",
  "Hip Hop---Trip Hop",
  "Hip Hop---Turntablism",
  "Jazz---Afro-Cuban Jazz",
  "Jazz---Afrobeat",
  "Jazz---Avant-garde Jazz",
  "Jazz---Big Band",
  "Jazz---Bop",
  "Jazz---Bossa Nova",
  "Jazz---Cape Jazz",
  "Jazz---Contemporary Jazz",
  "Jazz---Cool Jazz",
  "Jazz---Dixieland",
  "Jazz---Easy Listening",
  "Jazz---Free Improvisation",
  "Jazz---Free Jazz",
  "Jazz---Fusion",
  "Jazz---Gypsy Jazz",
  "Jazz---Hard Bop",
  "Jazz---Jazz-Funk",
  "Jazz---Jazz-Rock",
  "Jazz---Latin Jazz",
  "Jazz---Modal",
  "Jazz---Post Bop",
  "Jazz---Ragtime",
  "Jazz---Smooth Jazz",
  "Jazz---Soul-Jazz",
  "Jazz---Space-Age",
  "Jazz---Swing",
  "Latin---Afro-Cuban",
  "Latin---Axé",
  "Latin---Bachata",
  "Latin---Baião",
  "Latin---Batucada",
  "Latin---Beguine",
  "Latin---Bolero",
  "Latin---Boogaloo",
  "Latin---Bossanova",
  "Latin---Carimbó",
  "Latin---Cha-Cha",
  "Latin---Charanga",
  "Latin---Choro",
  "Latin---Compas",
  "Latin---Conjunto",
  "Latin---Corrido",
  "Latin---Cubano",
  "Latin---Cumbia",
  "Latin---Danzon",
  "Latin---Descarga",
  "Latin---Forró",
  "Latin---Gaita",
  "Latin---Guaguancó",
  "Latin---Guajira",
  "Latin---Guaracha",
  "Latin---Jibaro",
  "Latin---Lambada",
  "Latin---MPB",
  "Latin---Mambo",
  "Latin---Mariachi",
  "Latin---Marimba",
  "Latin---Merengue",
  "Latin---Música Criolla",
  "Latin---Norteño",
  "Latin---Nueva Cancion",
  "Latin---Nueva Trova",
  "Latin---Pachanga",
  "Latin---Plena",
  "Latin---Porro",
  "Latin---Quechua",
  "Latin---Ranchera",
  "Latin---Reggaeton",
  "Latin---Rumba",
  "Latin---Salsa",
  "Latin---Samba",
  "Latin---Samba-Canção",
  "Latin---Son",
  "Latin---Son Montuno",
  "Latin---Sonero",
  "Latin---Tango",
  "Latin---Tejano",
  "Latin---Timba",
  "Latin---Trova",
  "Latin---Vallenato",
  "Non-Music---Audiobook",
  "Non-Music---Comedy",
  "Non-Music---Dialogue",
  "Non-Music---Education",
  "Non-Music---Erotic",
  "Non-Music---Field Recording",
  "Non-Music---Health-Fitness",
  "Non-Music---Interview",
  "Non-Music---Monolog",
  "Non-Music---Movie Effects",
  "Non-Music---Poetry",
  "Non-Music---Political",
  "Non-Music---Promotional",
  "Non-Music---Public Broadcast",
  "Non-Music---Radioplay",
  "Non-Music---Religious",
  "Non-Music---Sermon",
  "Non-Music---Sound Art",
  "Non-Music---Sound Poetry",
  "Non-Music---Special Effects",
  "Non-Music---Speech",
  "Non-Music---Spoken Word",
  "Non-Music---Technical",
  "Non-Music---Therapy",
  "Pop---Ballad",
  "Pop---Barbershop",
  "Pop---Bollywood",
  "Pop---Break-In",
  "Pop---Bubblegum",
  "Pop---Chanson",
  "Pop---City Pop",
  "Pop---Enka",
  "Pop---Ethno-pop",
  "Pop---Europop",
  "Pop---Indie Pop",
  "Pop---J-pop",
  "Pop---K-pop",
  "Pop---Karaoke",
  "Pop---Kayōkyoku",
  "Pop---Levenslied",
  "Pop---Light Music",
  "Pop---Music Hall",
  "Pop---Novelty",
  "Pop---Parody",
  "Pop---Schlager",
  "Pop---Vocal",
  "Reggae---Calypso",
  "Reggae---Dancehall",
  "Reggae---Dub",
  "Reggae---Dub Poetry",
  "Reggae---Lovers Rock",
  "Reggae---Mento",
  "Reggae---Ragga",
  "Reggae---Reggae",
  "Reggae---Reggae Gospel",
  "Reggae---Reggae-Pop",
  "Reggae---Rocksteady",
  "Reggae---Roots Reggae",
  "Reggae---Ska",
  "Reggae---Soca",
  "Reggae---Steel Band",
  "Rock---AOR",
  "Rock---Acid Rock",
  "Rock---Acoustic",
  "Rock---Alternative Rock",
  "Rock---Arena Rock",
  "Rock---Art Rock",
  "Rock---Atmospheric Black Metal",
  "Rock---Avantgarde",
  "Rock---Beat",
  "Rock---Black Metal",
  "Rock---Blues Rock",
  "Rock---Brit Pop",
  "Rock---Classic Rock",
  "Rock---Coldwave",
  "Rock---Country Rock",
  "Rock---Crust",
  "Rock---Death Metal",
  "Rock---Deathcore",
  "Rock---Deathrock",
  "Rock---Depressive Black Metal",
  "Rock---Doo Wop",
  "Rock---Doom Metal",
  "Rock---Dream Pop",
  "Rock---Emo",
  "Rock---Ethereal",
  "Rock---Experimental",
  "Rock---Folk Metal",
  "Rock---Folk Rock",
  "Rock---Funeral Doom Metal",
  "Rock---Funk Metal",
  "Rock---Garage Rock",
  "Rock---Glam",
  "Rock---Goregrind",
  "Rock---Goth Rock",
  "Rock---Gothic Metal",
  "Rock---Grindcore",
  "Rock---Groove Metal",
  "Rock---Grunge",
  "Rock---Hard Rock",
  "Rock---Hardcore",
  "Rock---Heavy Metal",
  "Rock---Horror Rock",
  "Rock---Indie Rock",
  "Rock---Industrial",
  "Rock---Industrial Metal",
  "Rock---J-Rock",
  "Rock---Jangle Pop",
  "Rock---K-Rock",
  "Rock---Krautrock",
  "Rock---Lo-Fi",
  "Rock---Lounge",
  "Rock---Math Rock",
  "Rock---Melodic Death Metal",
  "Rock---Melodic Hardcore",
  "Rock---Metalcore",
  "Rock---Mod",
  "Rock---NDW",
  "Rock---Neofolk",
  "Rock---New Wave",
  "Rock---No Wave",
  "Rock---Noise",
  "Rock---Noisecore",
  "Rock---Nu Metal",
  "Rock---Oi",
  "Rock---Parody",
  "Rock---Pop Punk",
  "Rock---Pop Rock",
  "Rock---Pornogrind",
  "Rock---Post Rock",
  "Rock---Post-Hardcore",
  "Rock---Post-Metal",
  "Rock---Post-Punk",
  "Rock---Power Metal",
  "Rock---Power Pop",
  "Rock---Power Violence",
  "Rock---Prog Rock",
  "Rock---Progressive Metal",
  "Rock---Psychedelic Rock",
  "Rock---Psychobilly",
  "Rock---Pub Rock",
  "Rock---Punk",
  "Rock---Rock & Roll",
  "Rock---Rock Opera",
  "Rock---Rockabilly",
  "Rock---Shoegaze",
  "Rock---Ska",
  "Rock---Skiffle",
  "Rock---Sludge Metal",
  "Rock---Soft Rock",
  "Rock---Southern Rock",
  "Rock---Space Rock",
  "Rock---Speed Metal",
  "Rock---Stoner Rock",
  "Rock---Surf",
  "Rock---Swamp Pop",
  "Rock---Symphonic Rock",
  "Rock---Technical Death Metal",
  "Rock---Thrash",
  "Rock---Twist",
  "Rock---Viking Metal",
  "Rock---Yé-Yé",
  "Stage & Screen---Musical",
  "Stage & Screen---Score",
  "Stage & Screen---Soundtrack",
  "Stage & Screen---Theme"
];