notifications:
  email: false

language: cpp

sudo: required
services:
    - docker
env: DOCKER_IMAGE=mtgupf/essentia-emscripten:latest

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/essentia/ $DOCKER_IMAGE /essentia/build-bindings.sh
  - travis/deploy_builds.sh
