notifications:
  email: false

language: cpp

sudo: required
services:
    - docker
env: DOCKER_IMAGE=mtgupf/essentia-emscripten:2.1-beta6-dev

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/build-bindings.sh
  - travis/deploy_transfer.sh

deploy:
  provider: script
  script:
    travis/deploy_builds.sh
  on:
    branch: master
    condition: $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG
