/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCarousel: typeof import('bootstrap-vue-next/components/BCarousel')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next/components/BCarousel')['BCarouselSlide']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadioGroup']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    IBiArrowCounterclockwise: typeof import('~icons/bi/arrow-counterclockwise')['default']
    IBiBoxArrowUpRight: typeof import('~icons/bi/box-arrow-up-right')['default']
    IBiChevronCompactLeft: typeof import('~icons/bi/chevron-compact-left')['default']
    IBiChevronCompactRight: typeof import('~icons/bi/chevron-compact-right')['default']
    IBiDownload: typeof import('~icons/bi/download')['default']
    IBiPause: typeof import('~icons/bi/pause')['default']
    IBiPauseFill: typeof import('~icons/bi/pause-fill')['default']
    IBiPlay: typeof import('~icons/bi/play')['default']
    IBiPlayFill: typeof import('~icons/bi/play-fill')['default']
    IBiSearch: typeof import('~icons/bi/search')['default']
    IBiUpload: typeof import('~icons/bi/upload')['default']
    IBiVolumeMuteFill: typeof import('~icons/bi/volume-mute-fill')['default']
    IBiVolumeUpFill: typeof import('~icons/bi/volume-up-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
