/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCarousel: typeof import('bootstrap-vue-next/components/BCarousel')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next/components/BCarousel')['BCarouselSlide']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadioGroup']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    IBiArrowCounterclockwise: typeof import('~icons/bi/arrow-counterclockwise')['default']
    IBiBoxArrowUpRight: typeof import('~icons/bi/box-arrow-up-right')['default']
    IBiChevronCompactLeft: typeof import('~icons/bi/chevron-compact-left')['default']
    IBiChevronCompactRight: typeof import('~icons/bi/chevron-compact-right')['default']
    IBiDownload: typeof import('~icons/bi/download')['default']
    IBiPause: typeof import('~icons/bi/pause')['default']
    IBiPauseFill: typeof import('~icons/bi/pause-fill')['default']
    IBiPlay: typeof import('~icons/bi/play')['default']
    IBiPlayFill: typeof import('~icons/bi/play-fill')['default']
    IBiSearch: typeof import('~icons/bi/search')['default']
    IBiUpload: typeof import('~icons/bi/upload')['default']
    IBiVolumeMuteFill: typeof import('~icons/bi/volume-mute-fill')['default']
    IBiVolumeUpFill: typeof import('~icons/bi/volume-up-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardSubtitle: typeof import('vuetify/lib')['VCardSubtitle']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VExpansionPanel: typeof import('vuetify/lib')['VExpansionPanel']
    VExpansionPanels: typeof import('vuetify/lib')['VExpansionPanels']
    VExpansionPanelText: typeof import('vuetify/lib')['VExpansionPanelText']
    VExpansionPanelTitle: typeof import('vuetify/lib')['VExpansionPanelTitle']
    VOverlay: typeof import('vuetify/lib')['VOverlay']
    VProgressLinear: typeof import('vuetify/lib')['VProgressLinear']
    VRow: typeof import('vuetify/lib')['VRow']
    VSheet: typeof import('vuetify/lib')['VSheet']
    VSlideGroup: typeof import('vuetify/lib')['VSlideGroup']
    VSlideGroupItem: typeof import('vuetify/lib')['VSlideGroupItem']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VStepper: typeof import('vuetify/lib')['VStepper']
    VStepperHeader: typeof import('vuetify/lib')['VStepperHeader']
    VStepperItem: typeof import('vuetify/lib')['VStepperItem']
    VStepperWindow: typeof import('vuetify/lib')['VStepperWindow']
    VStepperWindowItem: typeof import('vuetify/lib')['VStepperWindowItem']
    VTable: typeof import('vuetify/lib')['VTable']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
  export interface GlobalDirectives {
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
